// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/:type-captcha': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/[type]-captcha.post').default>>>>
    }
    '/api/auth/forgot': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/forgot.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/login.post').default>>>>
    }
    '/api/auth/refresh': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/refresh.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/register.post').default>>>>
    }
    '/api/category/info': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/category/info.post').default>>>>
    }
    '/api/comm/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/comm/upload.post').default>>>>
    }
    '/api/comment/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/comment/create.post').default>>>>
    }
    '/api/comment/like': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/comment/like.post').default>>>>
    }
    '/api/comment/page': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/comment/page.post').default>>>>
    }
    '/api/dict/data': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/dict/data.post').default>>>>
    }
    '/api/external-link/click': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/external-link/click.post').default>>>>
    }
    '/api/ip/agent': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/ip/agent.post').default>>>>
    }
    '/api/ip/history': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/ip/history.post').default>>>>
    }
    '/api/ip/info': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/ip/info.post').default>>>>
    }
    '/api/my/collections': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/my/collections.post').default>>>>
    }
    '/api/my/history': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/my/history.post').default>>>>
    }
    '/api/my/tips': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/my/tips.post').default>>>>
    }
    '/api/news/article': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/news/article.post').default>>>>
    }
    '/api/news/categories': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/news/categories.post').default>>>>
    }
    '/api/news/collection': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/news/collection.post').default>>>>
    }
    '/api/news/like': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/news/like.post').default>>>>
    }
    '/api/news/list': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/news/list.post').default>>>>
    }
    '/api/news/page': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/news/page.post').default>>>>
    }
    '/api/tip/collection': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/tip/collection.post').default>>>>
    }
    '/api/tip/info': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/tip/info.post').default>>>>
    }
    '/api/tip/today': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/tip/today.post').default>>>>
    }
    '/api/user/change-phone': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/user/change-phone.post').default>>>>
    }
    '/api/user/email-binding': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/user/email-binding.post').default>>>>
    }
    '/api/user/email-verify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/user/email-verify.post').default>>>>
    }
    '/api/user/identity-verify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/user/identity-verify.post').default>>>>
    }
    '/api/user/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/user/logout.post').default>>>>
    }
    '/api/user/person': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/user/person.post').default>>>>
    }
    '/api/user/reset-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/user/reset-password.post').default>>>>
    }
    '/api/user/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/user/update.post').default>>>>
    }
    '/public/uploads/:date/:file': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/routes/public/uploads/[date]/[file]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}